"""Actions the assistant can ask the browser to perform.

Design rules, in priority order:

1. **Only existing app functionality.** Every action here maps onto a control
   that already exists in the running application (``setPage``, the sea-ice
   horizon dropdown, the iceberg list, the route cards, Start Journey, Advance
   2 Hours, Recalculate Route). Nothing is invented. In particular this system
   has no pause/resume, so there is no pause action - see ``UNSUPPORTED``.

2. **The backend never executes app state.** Actions are returned as data and
   carried out by the browser, which already owns that state. The backend has
   no way to move the user's vessel, so it must not pretend to.

3. **Validate before returning.** Parameters are checked and clamped here, so a
   hallucinated page name or a 900-hour horizon can never reach the app.

4. **Consequential actions ask first.** Starting a voyage, advancing time and
   recalculating a route change what the user will actually sail, so they
   return ``needs_confirmation`` and the UI renders Confirm/Cancel.

5. **No secrets, no code execution, no arbitrary endpoints.** The action type
   is drawn from a fixed set and the frontend switches on it; there is no path
   by which a model response can name a URL or run code.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Any, Callable

#: The pages the application actually has (App.tsx page switch).
PAGES: dict[str, str] = {
    "home": "Home",
    "sea-ice": "Sea-Ice Forecast",
    "icebergs": "Iceberg Tracking",
    "planner": "Navigation Dashboard",
    "alerts": "Alert Message",
    "assistant": "AI Assistant",
}

#: Horizons the Sea-Ice Forecast page offers (SeaIceForecast.tsx HORIZONS).
HORIZONS: tuple[int, ...] = (6, 12, 24, 48, 72, 120, 168)

#: Things people ask for that this application genuinely does not do.
#: Answering these honestly is required.
UNSUPPORTED: tuple[tuple[str, str], ...] = (
    (r"\bchange the (?:route|heading|course|waypoint)s?\b|\bplot a different route\b",
     "The route is generated by the navigation engine, not edited directly. Change the "
     "vessel, departure port or research centre and recalculate, or recalculate from a "
     "new live position - both are existing controls on the Navigation Dashboard."),
    (r"\bsave (?:the )?(?:route|alert|report)\b|\bexport\b|\bdownload\b|\bdelete (?:the )?route\b",
     "There's no save, export or delete control in this application, so I can't do that."),
)


class ActionError(ValueError):
    """A requested action was malformed or not permitted."""


@dataclass(frozen=True)
class Action:
    """One thing the assistant may ask the browser to do."""

    type: str
    label: str
    needs_confirmation: bool
    validate: Callable[[dict[str, Any]], dict[str, Any]]
    #: Phrase the confirmation prompt, given validated params and context.
    prompt: Callable[[dict[str, Any], Any], str] | None = None


# ----------------------------------------------------------------------
# Validators - each one either returns clean params or raises ActionError
# ----------------------------------------------------------------------
def _v_navigate(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    page = str(params.get("page", "")).strip()
    if page not in PAGES:
        raise ActionError(
            f"'{page}' is not a page in this application. The pages are: "
            + ", ".join(sorted(PAGES)) + "."
        )
    if ctx.page == page:
        raise ActionError(f"You're already on the {PAGES[page]} page.")
    return {"page": page}


def _v_horizon(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    raw = params.get("hours")
    try:
        hours = int(raw)
    except (TypeError, ValueError):
        raise ActionError("I need a forecast horizon in hours.") from None
    if hours not in HORIZONS:
        raise ActionError(
            f"{hours}h isn't one of the horizons this page offers. "
            f"Choose from {', '.join(f'{h}h' for h in HORIZONS)}."
        )
    return {"hours": hours}


def _v_select_iceberg(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    iceberg_id = str(params.get("iceberg_id", "")).strip().upper()
    if not iceberg_id:
        raise ActionError("I need an iceberg ID, for example DEMO-B001.")
    known = {i.get("iceberg_id") for i in (ctx.iceberg.get("items") or [])}
    if known and iceberg_id not in known and not iceberg_id.startswith("DEMO-"):
        raise ActionError(
            f"{iceberg_id} isn't in the tracked iceberg list right now "
            f"({len(known)} icebergs are loaded)."
        )
    return {"iceberg_id": iceberg_id}


def _v_select_route(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    which = str(params.get("which", "")).strip()
    available = ctx.navigation.get("routes_available") or []
    labels = [r.get("label") for r in available]
    key = which.lower()

    target = next((r for r in available if (r.get("label") or "").lower() == key), None)
    if target is None and key in ("recommended", "best", "main", "safest"):
        target = next((r for r in available if r.get("is_recommended")), None)
    if target is None:
        match = re.match(r"alternative:(\d+)", key)
        if match:
            wanted = int(match.group(1))
            target = next(
                (r for r in available
                 if re.search(rf"alternative\D*0*{wanted}\b", (r.get("label") or ""), re.I)),
                None,
            )
    if target is None:
        raise ActionError(
            "I need to know which route - say 'the recommended route' or "
            "'alternative route 1'. Available: " + (", ".join(labels) or "none yet")
        )
    return {
        "label": target.get("label"),
        "is_recommended": bool(target.get("is_recommended")),
    }


def _v_no_params(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    return {}


def _v_start_journey(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    nav = ctx.navigation
    origin = nav.get("port_id") or "hobart"
    dest = nav.get("center_id") or "mcmurdo"
    vessel = nav.get("vessel_id") or "polar_explorer"
    if ctx.journey_active:
        raise ActionError(
            f"A voyage is already running ({ctx.journey.get('origin')} → "
            f"{ctx.journey.get('destination')}). Use 'Advance 2 Hours' or "
            "'Recalculate Route' instead."
        )
    return {
        "origin": origin,
        "destination": dest,
        "vessel_id": vessel,
        "vessel_name": (ctx.vessel.get("name") or ctx.vessel_hint.get("name") or "Polar Explorer"),
        "journey_mode": nav.get("journey_mode") or "outbound",
    }


def _v_advance(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    if not ctx.journey_active:
        raise ActionError("There's no voyage running yet, so there's no time to advance.")
    step = ctx.navigation.get("time_step_hours") or 2
    return {"hours": step}


def _v_recalculate(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    if ctx.raw_dashboard and not ctx.navigation.get("journey"):
        raise ActionError("There's no voyage running to recalculate.")
    lat, lon = ctx.vessel_position
    if lat is None or lon is None:
        if ctx.raw_dashboard:
            raise ActionError("I don't have a vessel position to recalculate from.")
        lat, lon = -42.8826, 147.3257
    return {"lat": float(lat), "lon": float(lon)}


def _v_pause_journey(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    return {}


def _v_resume_journey(params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    return {}


# ----------------------------------------------------------------------
# Confirmation prompts
# ----------------------------------------------------------------------
def _p_start_journey(p: dict[str, Any], ctx: Any) -> str:
    vessel = p.get("vessel_name") or p.get("vessel_id") or "the selected vessel"
    mode = p.get("journey_mode") or "outbound"
    return (
        f"Start a {mode} voyage for {vessel} from {p['origin']} to "
        f"{p['destination']}, generating a route with the current sea-ice and "
        f"iceberg data?"
    )


def _p_advance(p: dict[str, Any], ctx: Any) -> str:
    return (
        f"Advance the voyage {p['hours']:g} simulated hours? The vessel moves along the "
        f"route and the route is recalculated from its new position."
    )


def _p_recalculate(p: dict[str, Any], ctx: Any) -> str:
    return (
        f"Recalculate the route from the vessel's current position "
        f"({p['lat']:.4f}, {p['lon']:.4f}) using the latest sea-ice and iceberg data?"
    )


ACTIONS: dict[str, Action] = {
    action.type: action
    for action in (
        Action("navigate", "Open a page", False, _v_navigate),
        Action("set_horizon", "Change forecast horizon", False, _v_horizon),
        Action("select_iceberg", "Select an iceberg", False, _v_select_iceberg),
        Action("select_route", "Select a route", False, _v_select_route),
        Action("mark_alerts_read", "Mark alerts as read", False, _v_no_params),
        Action("refresh_data", "Refresh page data", False, _v_no_params),
        Action("start_journey", "Start a voyage", True, _v_start_journey, _p_start_journey),
        Action("advance_journey", "Advance the voyage", True, _v_advance, _p_advance),
        Action("recalculate_route", "Recalculate the route", True, _v_recalculate, _p_recalculate),
        Action("pause_journey", "Pause the voyage", False, _v_pause_journey),
        Action("resume_journey", "Resume the voyage", False, _v_resume_journey),
    )
}

#: Actions that must never be suggested without the user asking for them.
#: Used by the intent detector so "show me the route" does not start a voyage.
ACTION_VERBS: tuple[tuple[str, str], ...] = (
    (r"\bnavigate\b|\bgo to\b|\bopen\b|\bshow me the \w+ page\b|\btake me to\b|\bswitch to\b",
     "navigate"),
    # The number can sit on either side of the noun: "72 hour forecast",
    # "forecast for 72h", "change the horizon to 72 hours".
    (r"\b(?:change|set|switch|show|display|give|give me|plot)\b[^.?]*\b(?:horizon|forecast|outlook|projection)\b",
     "set_horizon"),
    (r"\b(?:horizon|forecast|outlook|projection)\b[^.?]*\b(?:to|at|for|of)\b\s*(\d+)",
     "set_horizon"),
    (r"\b(\d+)\s*(?:h\b|hr|hrs|hour|hours)\s*(?:sea[\s-]?ice\s+)?(?:forecast|horizon|outlook|projection|view|data)\b",
     "set_horizon"),
    (r"\b(?:select|show|track|focus|open|look at)\b[^.?]*\b(?:iceberg|berg)\b", "select_iceberg"),
    (r"\bselect\b[^.?]*\broute\b|\bshow (?:me )?the (?:recommended|alternative) route\b",
     "select_route"),
    (r"\bmark\b[^.?]*\balerts? as read\b|\bclear (?:the )?alerts?\b", "mark_alerts_read"),
    (r"\brefresh\b|\breload\b", "refresh_data"),
    (r"\b(?:start|begin|launch)\b\s*(?:the\s+|a\s+|another\s+|new\s+)?"
     r"(?:journey|voyage|simulation|route)\b",
     "start_journey"),
    (r"\badvance\b[^.?]*\b(?:hours?|hrs?|step|time|journey)\b|\bstep forward\b",
     "advance_journey"),
    (r"\brecalculate\b|\bre-?plan\b|\bupdate the route\b", "recalculate_route"),
    (r"\bpause\b|\bfreeze\b|\bhold position\b", "pause_journey"),
    (r"\bresume\b|\bunpause\b|\bcontinue voyage\b|\bcontinue journey\b", "resume_journey"),
)

_ID_RE = re.compile(r"\b([A-Z]{2,6}-?[A-Z]?\d{2,5})\b")
_PAGE_WORDS: tuple[tuple[str, str], ...] = (
    (r"\bsea[\s-]?ice\b.*\b(forecast|page)\b|\bforecast page\b|\bsea ice forecast\b", "sea-ice"),
    (r"\biceberg\b.*\b(track|page)\b|\btracking page\b|\biceberg tracking\b", "icebergs"),
    (r"\bnavigation\b|\broute (?:page|dashboard)\b|\bopen navigation\b", "planner"),
    (r"\balerts?\b.*\bpage\b|\bmessage page\b|\balert page\b", "alerts"),
    (r"\bassistant\b|\bchat page\b", "assistant"),
    (r"\bhome\b|\bhomepage\b|\boverview page\b|\bmain page\b", "home"),
)


def _extract_horizon(question: str) -> int | None:
    """The horizon the user asked for, in hours.

    Returns the number they actually typed even when it is not one of the
    offered horizons - the validator then explains which ones exist, instead of
    the assistant asking a pointless follow-up question.
    """
    # "72h", "72 hours", "72-hour"
    match = re.search(r"(\d+)\s*-?\s*(?:h\b|hr|hrs|hour|hours)", question, re.IGNORECASE)
    if match:
        return int(match.group(1))
    # "horizon to 72", "forecast for 72", "set horizon of 72"
    match = re.search(
        r"\b(?:horizon|forecast|outlook|projection)\b[^.?]*?\b(?:to|at|for|of)\b\s*(\d+)",
        question,
        re.IGNORECASE,
    )
    if match:
        return int(match.group(1))
    # "72" on its own, but only if it is an offered horizon, so that an
    # unrelated number in the sentence is never mistaken for one.
    match = re.search(r"\b(\d+)\b", question)
    if match:
        value = int(match.group(1))
        if value in HORIZONS:
            return value
    return None


def _extract_page(question: str) -> str | None:
    q = question.lower()
    for pattern, page in _PAGE_WORDS:
        if re.search(pattern, q):
            return page
    return None


def _extract_route_ref(question: str, ctx: Any) -> str:
    """Which route the user means, as a label the validator understands.

    Returns one of: "recommended", "alternative:<n>", or an exact label from
    the routes currently on screen.
    """
    q = question.lower()
    labels = [r.get("label") for r in (ctx.navigation.get("routes_available") or [])]
    # Longest label first, so "Alternative Route 1" wins over "Alternative".
    for label in sorted((l for l in labels if l), key=len, reverse=True):
        if label.lower() in q:
            return label
    if re.search(r"\b(recommended|best|main|safest)\b", q):
        return "recommended"
    match = re.search(r"\balternative\s*(?:route\s*)?#?\s*(\d+)", q)
    if match:
        return f"alternative:{match.group(1)}"
    return question.strip()


def unsupported_answer(question: str) -> str | None:
    """Honest refusal for things this application cannot do."""
    q = question.lower()
    for pattern, message in UNSUPPORTED:
        if re.search(pattern, q):
            return message
    return None


@dataclass(frozen=True)
class ActionRequest:
    """The outcome of looking for actions in one question.

    ``recognised`` matters as much as the actions themselves: it is what lets
    the assistant say "I can't do that because..." instead of answering a
    request it never understood with an unrelated pile of data.
    """

    actions: list[dict[str, Any]]
    rejections: list[str]
    recognised: bool
    refusal: str | None = None

    def __bool__(self) -> bool:
        return bool(self.actions)


def resolve_actions(question: str, ctx: Any) -> ActionRequest:
    """Find action requests in natural language, validated against live state.

    Actions come back fully validated and ready to execute. Anything that fails
    validation comes back as a rejection explaining why, in plain language. A
    request the application genuinely cannot perform comes back as ``refusal``.

    This is the single entry point, so a caller cannot accidentally answer
    "pause the voyage" as though it could be done.
    """
    actions: list[dict[str, Any]] = []
    rejections: list[str] = []
    attempted: set[str] = set()
    recognised = False
    q = question.strip()

    refusal = unsupported_answer(q)
    if refusal:
        recognised = True

    def add(action_type: str, params: dict[str, Any]) -> None:
        # Several verb patterns can match one sentence ("set forecast to 96
        # hours" hits two). Only ever handle a given action type once.
        if action_type in attempted:
            return
        attempted.add(action_type)
        action = ACTIONS[action_type]
        try:
            clean = action.validate(params, ctx)
        except ActionError as exc:
            rejections.append(str(exc))
            return
        entry: dict[str, Any] = {
            "id": f"{action_type}:{len(actions)}",
            "type": action_type,
            "label": action.label,
            "params": clean,
            "needs_confirmation": action.needs_confirmation,
        }
        if action.needs_confirmation and action.prompt is not None:
            entry["confirmation_prompt"] = action.prompt(clean, ctx)
        actions.append(entry)

    for pattern, action_type in ACTION_VERBS:
        if not re.search(pattern, q, re.IGNORECASE):
            continue
        recognised = True

        if action_type == "navigate":
            page = _extract_page(q)
            if page:
                add("navigate", {"page": page})
            else:
                rejections.append(
                    "I can open Home, Sea-Ice Forecast, Iceberg Tracking, the Navigation "
                    "Dashboard, Alert Message or the AI Assistant page - which one?"
                )
        elif action_type == "set_horizon":
            hours = _extract_horizon(q)
            if hours is not None:
                # "Show me the 72 hour forecast" asked to *see* it, so the page
                # has to be on screen or the change is invisible.
                if (ctx.page != "sea-ice"
                        and re.search(r"\b(show|display|give me|let me see|see)\b", q, re.IGNORECASE)):
                    add("navigate", {"page": "sea-ice"})
                add("set_horizon", {"hours": hours})
            else:
                rejections.append(
                    "Which horizon? This page offers "
                    + ", ".join(f"{h}h" for h in HORIZONS) + "."
                )
        elif action_type == "select_iceberg":
            page_req = _extract_page(q)
            ids = _ID_RE.findall(q)
            iceberg_id = ids[0].upper() if ids else ctx.selected_iceberg_id
            if page_req == "icebergs" and not ids:
                pass
            elif iceberg_id:
                add("select_iceberg", {"iceberg_id": iceberg_id})
            else:
                rejections.append("Which iceberg? Give me an ID, for example DEMO-B001.")
        elif action_type == "select_route":
            add("select_route", {"which": _extract_route_ref(q, ctx)})
        else:
            add(action_type, {})

    return ActionRequest(actions, rejections, recognised, refusal)


def build_action(action_type: str, params: dict[str, Any], ctx: Any) -> dict[str, Any]:
    """Validate and package a single named action (used after confirmation)."""
    if action_type not in ACTIONS:
        raise ActionError(f"Unknown action '{action_type}'.")
    action = ACTIONS[action_type]
    clean = action.validate(params, ctx)
    entry: dict[str, Any] = {
        "id": f"{action_type}:0",
        "type": action_type,
        "label": action.label,
        "params": clean,
        "needs_confirmation": action.needs_confirmation,
    }
    if action.needs_confirmation and action.prompt is not None:
        entry["confirmation_prompt"] = action.prompt(clean, ctx)
    return entry
